server:
  port: 8084

spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

logging:
  level:
    root: INFO
    org.springframework.amqp: WARN # Riduce il rumore dei log di sistema RabbitMQ
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"