version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: shared-postgres
    ports:
      - "0.0.0.0:55432:5432"  # <-- QUESTA E' LA RIGA DA CAMBIARE
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agenda-network

volumes:
  pgdata:

networks:
  agenda-network:
    driver: bridge